---
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Create a local temp directory for docker build
  file:
    path: /tmp/keepalived_build/
    state: directory

- name: Copy Dockerfile
  copy:
    src: keepalived/Dockerfile
    dest: /tmp/keepalived_build/Dockerfile

- name: Build keepalived image
  docker_image: >
    name={{ keepalived_image }}
    tag={{ keepalived_image_tag }}
    path=/tmp/keepalived_build
    state=present

- name: Remove build directory
  file:
    path: /tmp/keepalived_build
    state: absent

- name: Generate random internal password
  shell: uuidgen
  run_once: true
  register: keepalived_internal_pass

- name: Generate random external password
  shell: uuidgen
  run_once: true
  register: keepalived_external_pass

- name: Creates directory
  file:
    path: /etc/keepalived
    state: directory

- name: Configure keepalived
  template:
    src: keepalived.cfg.j2
    dest: /etc/keepalived/keepalived.cfg

- name: Generate systemd keepalived file
  template:
    src: keepalived.service.j2
    dest: /etc/systemd/system/keepalived.service

- name: Generate healthcheck script
  template:
    src: healthcheck-keepalived.sh.j2
    dest: /etc/keepalived/healthcheck-keepalived.sh
    mode: "o+rx"

- name: Allow VRRP connectivity
  iptables:
    state: present
    chain: INPUT
    protocol: vrrp
    jump: ACCEPT
    comment: Keepalived connectivity

- lineinfile:
    path: /etc/sysconfig/iptables-config
    regexp: '^IPTABLES_SAVE_ON_STOP='
    line: 'IPTABLES_SAVE_ON_STOP="yes"'

- lineinfile:
    path: /etc/sysconfig/iptables-config
    regexp: '^IPTABLES_SAVE_ON_RESTART='
    line: 'IPTABLES_SAVE_ON_RESTART="yes"'

- name: Start keepalived
  systemd:
    name: keepalived
    state: restarted
    enabled: yes
    daemon_reload: yes

