---
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "docker-python"
    - "ipxe-bootimgs"
    - "docker"
    - "python-docker-py"
    - "python-urllib3"

- name: Ensure docker is started
  systemd:
    name: docker
    enabled: yes
    state: started

- name: build nginx image
  docker_image: >
    name={{nginx_image}}
    tag={{ nginx_image_tag }}
    path={{playbook_dir}}/roles/deploy_ipxe/files/nginx/
    state=present

- name: build dnsmasq image
  docker_image: >
    name={{ dnsmasq_image }}
    tag={{ dnsmasq_image_tag }}
    path={{playbook_dir}}/roles/deploy_ipxe/files/dnsmasq/
    state=present

- name: Create dnsmasq config file
  template:
    src: dnsmasq_c.conf.j2
    dest: /etc/dnsmasq_c.conf

- name: Populate DNS entries
  template:
    src: "hosts.j2"
    dest: "/etc/dnsmasq.d/hosts"
    owner: root
    group: root
    mode: 0644

- name: Create dnsmasq systemd unit
  template:
    src:  dnsmasq_container.service.j2
    dest: /etc/systemd/system/dnsmasq_container.service

- name: Create nginx systemd unit
  template:
    src:  nginx_container.service.j2
    dest: /etc/systemd/system/nginx_container.service

- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/etc/dnsmasq.d"
    - "/tftp"
    - "/tftp/ipxe/serial"
    - "/tftp/atomic/media"
    - "/tftp/rhel/media"

- name: Copy undionly iPXE image
  copy:
    src: /usr/share/ipxe/ipxe.efi
    dest: /tftp/ipxe/ipxe.efi
    mode: 0644

- name: Create reboot script
  template:
    src:  reboot.sh
    dest: /tftp/reboot.sh

- name: Make reboot.sh executable
  file: dest=/tftp/reboot.sh mode=a+x

- name: Create ipxe main config systemd unit
  template:
    src:  main.ipxe.j2
    dest: /tftp/ipxe/main.ipxe

- name: Set Selinux labels
  command: chcon -Rt svirt_sandbox_file_t /tftp

- name: Start and enable nginx_container service
  systemd:
    name: nginx_container.service
    state: started
    enabled: True
    daemon_reload: yes

- name: Modify local resolvconf
  lineinfile:
    dest: /etc/resolv.conf
    state: present
    line: "nameserver 127.0.0.1"

- name: Start dnsmasq_container service
  systemd:
    name: dnsmasq_container.service
    state: started
    enabled: True
    daemon_reload: yes
