---
# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Create ipmi.list.txt
  template:
    src: ipmi.list.txt.j2
    dest: /tftp/ipmi.list.txt

- name: Create Atomic kickstarts
  template:
    src: atomic.ks.j2
    dest: /tftp/atomic/media/atomic-{{ item }}.ks
  with_items: "{{ groups.nodes }}"
  when: (hostvars[item]['os'] is defined) and (hostvars[item]['os'] == "atomic")

- name: Create RHEL kickstarts
  template:
    src: rhel.ks.j2
    dest: /tftp/rhel/media/rhel-{{ item }}.ks
  with_items: "{{ groups.nodes }}"
  when: hostvars[item]['os'] is undefined

- name: Create iPXE configs for Atomic
  template:
    src: serial.atomic.ipxe.j2
    dest: /tftp/ipxe/serial/{{ hostvars[item]['serial'] }}.ipxe
  with_items: "{{ groups.nodes }}"
  when: (hostvars[item]['os'] is defined) and (hostvars[item]['os'] == "atomic")

- name: Create iPXE configs for RHEL
  template:
    src: serial.rhel.ipxe.j2
    dest: /tftp/ipxe/serial/{{ hostvars[item]['serial'] }}.ipxe
  with_items: "{{ groups.nodes }}"
  when: hostvars[item]['os'] is undefined
